"""Thumbnail generation jobs + orphan GC (S12/P12 slice 1).

The DB/queue layer over the pure ``filearr.thumbs`` core. Three surfaces:

  * ``generate_and_store`` -- the shared engine: resolve a source (sidecar artwork
    FIRST, then per-media-type), encode via ``filearr.thumbs``, write the file
    atomically, and upsert the ``thumbnail_manifest`` row. Reused by the
    ride-along job AND the serve-path inline-on-miss generator.
  * ``thumb_item`` -- the ``thumbs``-queue task (priority ``thumbs_priority`` = -15)
    that pregenerates the GRID tier at extract ride-along (deferred post-commit by
    ``extract_item``, so it inherits the staged-pipeline discipline -- it only ever
    runs after a file's extraction wave has committed, never mid-walk).
  * ``gc_thumbnails`` -- the mandatory daily orphan GC (research §4 / the Nextcloud
    postmortem): reclaims files whose manifest row is gone AND rows whose backing
    file/item is gone. Bounded per run.

Source resolution order (research §3 "Rule 0"):
  1. a T3-linked artwork sidecar (``poster.jpg``/``-thumb.jpg`` etc.) -- zero
     compute, often better quality than a decoded frame;
  2. image item -> its own file;
  3. audio/audiobook/sample -> mutagen embedded cover art.
Video frames (ffmpeg/QSV, P12 slice 2) slot in as another source, BELOW the
sidecar-artwork branch (a video with a poster.jpg uses the poster, no ffmpeg
call). PDF documents render their first page (pypdfium2, P12-T5); other documents,
spreadsheets and 3D models get no thumbnail (placeholder icon).
"""

from __future__ import annotations

import logging
import os
import tempfile
from pathlib import PurePath

from sqlalchemy import select

from filearr import diskguard
from filearr import thumbs as th
from filearr.config import get_settings
from filearr.db import SessionLocal
from filearr.models import Item, MediaType, ThumbnailManifest
from filearr.sidecar import classify
from filearr.worker import proc_app

log = logging.getLogger("filearr.thumbs")

# Media types whose thumbnail can be generated by MEDIA TYPE alone. Image +
# audio-cover are slice 1; video poster-frames are slice 2 (ffmpeg). ``document``
# is NOT here -- it is eligible only for a ``.pdf`` extension (handled inside
# ``is_thumbnailable``); spreadsheet/model3d/other get a client placeholder icon.
_AUDIO_TYPES = frozenset({MediaType.audio, MediaType.audiobook, MediaType.sample})
_THUMBNAILABLE = frozenset({MediaType.image, MediaType.video}) | _AUDIO_TYPES


def is_thumbnailable(media_type: MediaType, rel_path: str | None = None) -> bool:
    """Whether the pipeline can produce a thumbnail for this item at all (before
    sidecar resolution). Used to gate the extract ride-along defer.

    Image/audio (slice 1) and video (slice 2) are eligible by media type alone.
    ``document`` is eligible ONLY for a ``.pdf`` extension (P12-T5): the
    ``document`` bucket also holds docx/odt/rtf/txt/md/epub/mobi/cbz -- none of
    which has a safe cheap render primitive, so they get the client placeholder
    icon (LibreOffice/office-doc rendering is explicitly out of Phase 12 scope,
    a later slice). ``rel_path`` supplies the extension for that gate; without it
    (a media-type-only probe) ``document`` reports not-thumbnailable so a caller
    can never blindly enqueue every doc. Spreadsheet/model3d/other: no thumbnail.
    """
    if media_type == MediaType.document:
        return rel_path is not None and PurePath(rel_path).suffix.lower() == ".pdf"
    return media_type in _THUMBNAILABLE


async def _artwork_sidecar_path(session, item: Item) -> str | None:
    """Return the path of a linked artwork sidecar (rule 0), or ``None``.

    A sidecar's *kind* is not persisted, so we re-derive it lexically with the
    pure ``sidecar.classify`` (the same deterministic classifier the scan used to
    link it) and accept the first ``artwork`` child whose file exists on disk.
    """
    children = (
        await session.execute(select(Item).where(Item.sidecar_of == item.id))
    ).scalars().all()
    for child in children:
        info = classify(child.rel_path)
        if info is not None and info.kind == "artwork" and os.path.exists(child.path):
            return child.path
    return None


async def _resolve_source(session, item: Item, tier: int, settings):
    """Resolve a source and produce encoded ``ThumbBytes`` for ``tier``.

    Returns ``(source_label, ThumbBytes)`` or ``None`` when no source is available
    or the source is undecodable/over-cap. ``source_label`` is persisted in the
    manifest ``source`` column.
    """
    # Rule 0: sidecar artwork wins for ANY parent media type.
    art = await _artwork_sidecar_path(session, item)
    if art is not None:
        tb = th.generate_image_thumb(art, tier, settings)
        if tb is not None:
            return "artwork", tb
        # A broken/oversized sidecar falls through to native generation below.

    if item.media_type == MediaType.image:
        tb = th.generate_image_thumb(item.path, tier, settings)
        if tb is not None:
            return "image", tb
        return None

    if item.media_type in _AUDIO_TYPES:
        raw = th.extract_audio_cover(item.path)
        if raw:
            tb = th.generate_thumb_from_bytes(raw, tier, settings)
            if tb is not None:
                return "audio_embedded", tb
        return None

    if item.media_type == MediaType.video:
        # Poster-frame via ffmpeg (P12 slice 2). Duration + HDR come straight from
        # the ffprobe pass already recorded in metadata_ -- no second probe (the
        # research §generation ruling). Missing duration -> min-seek fallback.
        meta = item.metadata_ or {}
        d = meta.get("duration")
        duration = float(d) if isinstance(d, (int, float)) and d > 0 else None
        hdr = bool(meta.get("hdr"))
        tb = th.generate_video_thumb(item.path, tier, duration, settings, hdr=hdr)
        if tb is not None:
            return "video", tb
        return None

    if item.media_type == MediaType.document:
        # PDF first-page via pypdfium2 (P12-T5). ONLY ``.pdf`` renders -- every
        # other document extension (docx/epub/txt/cbz/...) has no safe cheap
        # render primitive and falls through to the client placeholder icon.
        # In-process + sub-second, so (unlike video) the serve path generates it
        # INLINE on a miss -- no queue round-trip needed.
        if PurePath(item.rel_path).suffix.lower() == ".pdf":
            tb = th.generate_pdf_thumb(item.path, tier, settings)
            if tb is not None:
                return "pdf", tb
        return None

    # Everything else (spreadsheet/model3d/other): slice 3+ / placeholder icon.
    return None


def _atomic_write(path: str, data: bytes) -> None:
    """Write ``data`` to ``path`` atomically (temp file in the same dir + rename).

    Idempotent by content addressing: two workers writing the same cache key write
    byte-identical content, so a lost race is harmless. Sync IO mirrors the
    extract task's file handling (media/config mounts, small payloads)."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path), suffix=".tmp")
    try:
        with os.fdopen(fd, "wb") as fh:  # noqa: ASYNC230 - bounded local write
            fh.write(data)
        os.replace(tmp, path)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise


async def generate_and_store(
    session, item: Item, tier: int, settings=None
) -> ThumbnailManifest | None:
    """Generate a ``tier`` thumbnail for ``item`` and upsert its manifest row.

    Returns the (committed-by-caller) manifest row, or ``None`` when no source is
    available/decodable. The caller owns the transaction commit. Content-addressed:
    the cache key is derived from the item's current ``content_hash`` (fallback
    ``quick_hash``); a file with neither hashed yet is skipped (its thumbnail is
    produced once extraction sets a hash).
    """
    settings = settings or get_settings()
    hash_used = item.content_hash or item.quick_hash
    if not hash_used:
        return None

    resolved = await _resolve_source(session, item, tier, settings)
    if resolved is None:
        return None
    source_label, tb = resolved

    key = th.cache_key(hash_used, settings.thumbnail_generator_version, tier)
    path = th.abs_path(settings, key)
    # FIX-11 fail-closed guard: refuse to write a thumbnail when the cache
    # filesystem is at the CRITICAL low-space floor. This is the exact producer
    # that filled /config and crashed Postgres in the live incident. Raising
    # DiskGuardError here propagates out of thumb_item (the job fails with the
    # unambiguous 'disk_full_guard' token, no retry loop) and is caught by the
    # serve path (rendered as a 404, never a 500). Cheap: cached statvfs (~5s).
    diskguard.guard_write(th.thumbs_root(settings), settings)
    try:
        _atomic_write(path, tb.data)
    except OSError:
        log.warning("thumb write failed for item %s tier %s", item.id, tier)
        return None

    row = (
        await session.execute(
            select(ThumbnailManifest).where(
                ThumbnailManifest.item_id == item.id,
                ThumbnailManifest.tier == tier,
            )
        )
    ).scalar_one_or_none()
    if row is None:
        row = ThumbnailManifest(item_id=item.id, tier=tier)
        session.add(row)
    row.cache_key = key
    row.bytes = len(tb.data)
    row.width = tb.width
    row.height = tb.height
    row.source = source_label
    return row


async def store_agent_thumb(
    session,
    item: Item,
    tier: int,
    data: bytes,
    *,
    width: int | None = None,
    height: int | None = None,
    settings=None,
) -> tuple[ThumbnailManifest, bool] | None:
    """Store an AGENT-GENERATED thumbnail blob for ``item`` at ``tier`` via the
    SAME write-if-absent, content-addressed path central generation uses (P12-T13).

    An agent (which holds the source file central cannot reach) generates the
    thumbnail itself and pushes the encoded bytes here. Central re-derives the
    cache key from ITS OWN catalog row (``content_hash`` fallback ``quick_hash``) —
    identical to the agent's derivation because both come from the agent's scan —
    so two agents holding the same file by hash dedup to ONE blob. Returns
    ``(manifest_row, created)`` where ``created`` is True when a new file was
    written OR a new manifest row inserted (201 vs 200), or ``None`` when the item
    has no hash to key on (the caller 409s).

    The bytes are stored VERBATIM (the agent already ran the encode + byte-cap
    ladder); central does not re-encode. The caller has already validated the size
    cap, image-decodability, and item ownership."""
    settings = settings or get_settings()
    hash_used = item.content_hash or item.quick_hash
    if not hash_used:
        return None

    key = th.cache_key(hash_used, settings.thumbnail_generator_version, tier)
    path = th.abs_path(settings, key)
    file_exists = os.path.exists(path)
    if not file_exists:
        # Fail-closed on the critical low-space floor (same FIX-11 guard as
        # generate_and_store): raises DiskGuardError, caught by the endpoint.
        diskguard.guard_write(th.thumbs_root(settings), settings)
        _atomic_write(path, data)

    row = (
        await session.execute(
            select(ThumbnailManifest).where(
                ThumbnailManifest.item_id == item.id,
                ThumbnailManifest.tier == tier,
            )
        )
    ).scalar_one_or_none()
    created = row is None or not file_exists
    if row is None:
        row = ThumbnailManifest(item_id=item.id, tier=tier)
        session.add(row)
    row.cache_key = key
    row.bytes = len(data)
    row.width = width
    row.height = height
    row.source = "agent"
    return row, created


@proc_app.task(
    queue=get_settings().queue_thumbnail,
    name="filearr.tasks.thumbs.thumb_item",
    priority=get_settings().thumbs_priority,
)
async def thumb_item(item_id: str, tier: int = th.TIER_GRID) -> None:
    """Generate one tier for one item on the low-priority thumbs queue.

    Defaults to the GRID tier (the extract ride-along pregenerates grid). The
    ``preview`` tier stays lazy for cheap in-process sources (generated inline on
    the first serve-path miss), but the serve path enqueues THIS task for a VIDEO
    miss instead -- ffmpeg's latency variance must never block a request handler
    (research: video on-miss is queued+polled, never synchronous inline).
    """
    settings = get_settings()
    if not settings.thumbs_enabled:
        return
    async with SessionLocal() as session:
        item = (
            await session.execute(select(Item).where(Item.id == item_id))
        ).scalar_one_or_none()
        if item is None:
            return
        await generate_and_store(session, item, tier, settings)
        await session.commit()


# --- orphan GC (mandatory; research §4) ------------------------------------- #

@proc_app.periodic(cron="30 3 * * *")
@proc_app.task(queue="maintenance", name="filearr.tasks.thumbs.gc_thumbnails")
async def gc_thumbnails(timestamp: int) -> dict:
    """Daily orphan GC (periodic entrypoint). Delegates to :func:`run_thumbnail_gc`
    in the default (non-aggressive) mode so the FIX-11 emergency monitor can reuse
    the same engine in aggressive/LRU mode."""
    return await run_thumbnail_gc()


async def run_thumbnail_gc(
    *, aggressive: bool = False, target_free_bytes: int = 0
) -> dict:
    """Reclaim thumbnail cache space; the shared engine behind the daily GC AND
    the FIX-11 emergency pass.

    Two directions, both bounded and best-effort (a filesystem hiccup logs but
    never fails the run):

      * ROW orphans -- a manifest row whose owning item is gone (anti-join; a
        near-noop under the FK CASCADE but explicit belt-and-braces) OR whose
        backing file has vanished from disk (stale projection). The file is
        removed (if any) and the row deleted so the thumbnail is regenerated on
        next demand.
      * FILE orphans -- a ``.webp`` under the fanout whose cache key is not
        referenced by any manifest row (the classic post-regeneration leftover).
        Removed. The walk is capped at ``thumbnail_gc_max_files`` per run so a
        multi-million-file cache is swept incrementally.

    FIX-11 aggressive mode (``aggressive=True``): after the orphan sweep, if
    ``target_free_bytes`` > 0 and the cache filesystem still has less than that
    free, LRU-EVICT valid thumbnails oldest-first (by ``generated_at``) until the
    target is met or the cache is empty. Thumbnails are a DISPOSABLE projection
    (invariant 1), so eviction only costs a later regeneration — an acceptable
    trade to keep Postgres/Meili from running the volume dry.

    Returns/logs counters {rows_removed, files_removed, bytes_reclaimed,
    evicted}.
    """
    from sqlalchemy import delete

    settings = get_settings()
    root = th.thumbs_root(settings)
    rows_removed = 0
    files_removed = 0
    bytes_reclaimed = 0
    evicted = 0

    async with SessionLocal() as session:
        rows = (await session.execute(select(ThumbnailManifest))).scalars().all()
        live_item_ids = set(
            (await session.execute(select(Item.id))).scalars().all()
        )
        referenced: set[str] = set()
        stale_ids: list = []
        for row in rows:
            path = th.abs_path(settings, row.cache_key)
            item_gone = row.item_id not in live_item_ids
            file_gone = not os.path.exists(path)
            if item_gone or file_gone:
                if not file_gone:
                    try:
                        bytes_reclaimed += os.path.getsize(path)
                        os.remove(path)
                        files_removed += 1
                    except OSError:
                        pass
                stale_ids.append(row.id)
                rows_removed += 1
            else:
                referenced.add(row.cache_key)
        if stale_ids:
            await session.execute(
                delete(ThumbnailManifest).where(ThumbnailManifest.id.in_(stale_ids))
            )
            await session.commit()

    # FILE orphans: walk the fanout, delete any .webp not referenced by a row.
    scanned = 0
    if os.path.isdir(root):
        for dirpath, _dirs, files in os.walk(root):
            for name in files:
                if not name.endswith(".webp"):
                    continue
                scanned += 1
                if scanned > settings.thumbnail_gc_max_files:
                    break
                key = name[: -len(".webp")]
                if key in referenced:
                    continue
                fpath = os.path.join(dirpath, name)
                try:
                    bytes_reclaimed += os.path.getsize(fpath)
                    os.remove(fpath)
                    files_removed += 1
                except OSError:
                    pass
            if scanned > settings.thumbnail_gc_max_files:
                break

    # FIX-11 emergency LRU eviction of VALID thumbnails (aggressive mode only).
    if aggressive and target_free_bytes > 0:
        evicted, ev_bytes = await _lru_evict_to_target(settings, root, target_free_bytes)
        bytes_reclaimed += ev_bytes

    result = {
        "rows_removed": rows_removed,
        "files_removed": files_removed,
        "bytes_reclaimed": bytes_reclaimed,
        "evicted": evicted,
    }
    log.info("gc_thumbnails reclaimed %s", result)
    return result


async def _lru_evict_to_target(settings, root: str, target_free_bytes: int):
    """Evict valid thumbnails oldest-first until the cache fs has ``target_free_
    bytes`` free (or the cache is empty). Returns (evicted_count, bytes_freed).

    Bounded by ``thumbnail_gc_max_files`` per pass. Rechecks free space every 200
    deletions so it stops the instant the target is met (never over-evicts)."""
    from sqlalchemy import delete

    evicted = 0
    freed = 0
    try:
        if diskguard.disk_status(root)["free"] >= target_free_bytes:
            return 0, 0
    except OSError:
        return 0, 0

    async with SessionLocal() as session:
        rows = (
            await session.execute(
                select(ThumbnailManifest)
                .order_by(ThumbnailManifest.generated_at.asc())
                .limit(settings.thumbnail_gc_max_files)
            )
        ).scalars().all()
        removed_ids: list = []
        for i, row in enumerate(rows):
            path = th.abs_path(settings, row.cache_key)
            try:
                freed += os.path.getsize(path)
                os.remove(path)
            except OSError:
                pass
            removed_ids.append(row.id)
            evicted += 1
            # Recheck headroom periodically so we stop as soon as the target is met.
            if (i + 1) % 200 == 0:
                try:
                    if diskguard.disk_status(root)["free"] >= target_free_bytes:
                        break
                except OSError:
                    break
        if removed_ids:
            await session.execute(
                delete(ThumbnailManifest).where(
                    ThumbnailManifest.id.in_(removed_ids)
                )
            )
            await session.commit()
    if evicted:
        log.warning("emergency thumbnail LRU eviction: removed %d thumbnails", evicted)
    return evicted, freed
