"""baseline schema

Revision ID: 2bfb3fd1d09a
Revises: 
Create Date: 2026-07-06 23:45:43.103866
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '2bfb3fd1d09a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Postgres 18+ required: uuidv7() primary-key defaults. Fail fast and clearly.
    op.execute("SELECT uuidv7()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('prefix', sa.Text(), nullable=False),
    sa.Column('key_hash', sa.Text(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{read}'"), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prefix')
    )
    op.create_table('libraries',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('root_path', sa.Text(), nullable=False),
    sa.Column('enabled_types', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('include_globs', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('exclude_globs', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('native_prefix', sa.Text(), nullable=True),
    sa.Column('scan_cron', sa.Text(), nullable=True),
    sa.Column('watch_mode', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('media_type', sa.Enum('video', 'audio', 'audiobook', 'sample', 'image', 'model3d', 'document', 'spreadsheet', 'other', name='media_type'), nullable=False),
    sa.Column('status', sa.Enum('active', 'missing', 'trashed', name='item_status'), server_default='active', nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('filename', sa.Text(), nullable=False),
    sa.Column('extension', sa.Text(), nullable=True),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('mtime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('quick_hash', sa.Text(), nullable=True),
    sa.Column('content_hash', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('external_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('user_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('first_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_items_library_rel_path', 'items', ['library_id', 'rel_path'], unique=True)
    op.create_index('ix_items_media_type', 'items', ['media_type'], unique=False)
    op.create_index('ix_items_metadata', 'items', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index('ix_items_quick_hash', 'items', ['quick_hash'], unique=False)
    op.create_index('ix_items_status', 'items', ['status'], unique=False)
    op.create_index('ix_items_tags', 'items', ['tags'], unique=False, postgresql_using='gin')
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('library_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), server_default=sa.text("'running'"), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuidv7()'), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('actor', sa.Text(), nullable=False),
    sa.Column('patch', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_item_versions_item_id'), 'item_versions', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_item_versions_item_id'), table_name='item_versions')
    op.drop_table('item_versions')
    op.drop_table('scan_runs')
    op.drop_index('ix_items_tags', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_status', table_name='items')
    op.drop_index('ix_items_quick_hash', table_name='items')
    op.drop_index('ix_items_metadata', table_name='items', postgresql_using='gin')
    op.drop_index('ix_items_media_type', table_name='items')
    op.drop_index('ix_items_library_rel_path', table_name='items')
    op.drop_table('items')
    op.drop_table('libraries')
    op.drop_table('api_keys')
    sa.Enum(name='media_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='item_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
