package thumbs

import "testing"

// TestCacheKeyParity pins the agent's CacheKey against values CENTRAL computed
// with its exact rule (backend/filearr/thumbs.py:cache_key —
// blake2b(f"{hash}:{gen}:{tier}", digest_size=16).hexdigest()). A drift here means
// the agent writes thumbnails under keys central never looks up, so this is the
// load-bearing content-addressing contract test. Vectors were generated by
// running central's cache_key directly.
func TestCacheKeyParity(t *testing.T) {
	cases := []struct {
		hash string
		gen  int
		tier int
		want string
	}{
		{"deadbeef", 1, TierGrid, "0721d5d66385239c64085a00d7aa53a9"},
		{"deadbeef", 1, TierPreview, "95859cd77f17d7452bb00e64aba577c3"},
		{"0123456789abcdef0123456789abcdef", 1, TierGrid, "8e9cf639499b0f4c0bb92af562fded9b"},
		{"abc123", 2, TierPreview, "0c55c1fe0810a18e641073f8e4c81c21"},
	}
	for _, c := range cases {
		got := CacheKey(c.hash, c.gen, c.tier)
		if got != c.want {
			t.Errorf("CacheKey(%q,%d,%d) = %s, want %s (central parity)", c.hash, c.gen, c.tier, got, c.want)
		}
		if len(got) != 32 {
			t.Errorf("CacheKey length = %d, want 32", len(got))
		}
	}
}

// TestFanoutParity pins the on-disk layout against central's fanout_path
// ("ab/cd/<key>.webp") and asserts the traversal guard rejects a non-hex key.
func TestFanoutParity(t *testing.T) {
	key := "0721d5d66385239c64085a00d7aa53a9"
	got, err := FanoutPath(key)
	if err != nil {
		t.Fatalf("FanoutPath: %v", err)
	}
	want := "07/21/0721d5d66385239c64085a00d7aa53a9.webp"
	if got != want {
		t.Fatalf("FanoutPath = %s, want %s", got, want)
	}

	for _, bad := range []string{"../../etc/passwd", "AB/CD", "gg", "", "abc"} {
		if _, err := FanoutPath(bad); err == nil {
			t.Errorf("FanoutPath(%q) should reject a non-hex/short key", bad)
		}
	}
}
